#!/bin/bash

# Script to configure GitHub Secrets using GitHub CLI
# Usage: ./scripts/configure-github-secrets.sh <secrets-file>
#   secrets-file: Path to file containing secrets (generated by generate-secrets.sh)

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}Error: GitHub CLI (gh) is not installed${NC}"
    echo ""
    echo "Install GitHub CLI:"
    echo "  macOS:   brew install gh"
    echo "  Ubuntu:  sudo apt install gh"
    echo "  Other:   https://cli.github.com/manual/installation"
    echo ""
    echo "After installation, authenticate with:"
    echo "  gh auth login"
    exit 1
fi

# Check if authenticated
if ! gh auth status > /dev/null 2>&1; then
    echo -e "${RED}Error: Not authenticated with GitHub${NC}"
    echo ""
    echo "Please authenticate with:"
    echo "  gh auth login"
    exit 1
fi

# Check if secrets file provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: Secrets file not provided${NC}"
    echo ""
    echo "Usage: $0 <secrets-file>"
    echo ""
    echo "First generate secrets:"
    echo "  ./scripts/generate-secrets.sh staging"
    echo ""
    echo "Then configure them:"
    echo "  $0 secrets-staging-YYYYMMDD-HHMMSS.txt"
    exit 1
fi

SECRETS_FILE="$1"

if [ ! -f "$SECRETS_FILE" ]; then
    echo -e "${RED}Error: Secrets file not found: $SECRETS_FILE${NC}"
    exit 1
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Configure GitHub Secrets via CLI                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}This will configure secrets from: ${SECRETS_FILE}${NC}"
echo ""

# Get repository
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
echo -e "Repository: ${CYAN}${REPO}${NC}"
echo ""

read -p "Continue? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Cancelled"
    exit 0
fi

echo ""
echo -e "${CYAN}Configuring secrets...${NC}"
echo ""

# Counter
SUCCESS=0
FAILED=0
SKIPPED=0

# Read secrets file and configure each secret
while IFS='=' read -r key value; do
    # Skip comments and empty lines
    if [[ "$key" =~ ^#.* ]] || [ -z "$key" ]; then
        continue
    fi

    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)

    # Skip if value is placeholder
    if [[ "$value" =~ ^rzp_test_xxxx.* ]] || [[ "$value" =~ ^your_.* ]] || [[ "$value" =~ ^https://xxx.* ]]; then
        echo -e "${YELLOW}⊘ Skipping ${key} (placeholder value)${NC}"
        ((SKIPPED++))
        continue
    fi

    # Configure secret
    echo -n "Setting ${key}... "
    if echo "$value" | gh secret set "$key" --repo "$REPO" 2>/dev/null; then
        echo -e "${GREEN}✓${NC}"
        ((SUCCESS++))
    else
        echo -e "${RED}✗${NC}"
        ((FAILED++))
    fi
done < "$SECRETS_FILE"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Summary${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Configured: ${GREEN}${SUCCESS}${NC}"
echo -e "Failed: ${RED}${FAILED}${NC}"
echo -e "Skipped: ${YELLOW}${SKIPPED}${NC} (placeholder values)"
echo ""

if [ $FAILED -gt 0 ]; then
    echo -e "${YELLOW}Some secrets failed to configure. Configure them manually:${NC}"
    echo -e "${CYAN}https://github.com/${REPO}/settings/secrets/actions${NC}"
    echo ""
fi

if [ $SKIPPED -gt 0 ]; then
    echo -e "${YELLOW}Skipped secrets need to be configured manually with real values:${NC}"
    echo "  - Razorpay keys: Get from https://dashboard.razorpay.com/"
    echo "  - Sentry DSN: Get from https://sentry.io/"
    echo ""
fi

echo -e "${GREEN}Next Steps:${NC}"
echo ""
echo "1. Configure any skipped secrets manually (optional for testing)"
echo ""
echo "2. Verify secrets are configured:"
echo -e "   ${CYAN}gh secret list --repo ${REPO}${NC}"
echo ""
echo "3. Test staging deployment:"
echo -e "   ${CYAN}git checkout develop${NC}"
echo -e "   ${CYAN}git push origin develop${NC}"
echo ""

exit 0
